name: RDKit CFFI Windows VS 2024.09

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with debug logging'
        required: false
        default: false
        type: boolean
  # push:
  #   branches:
  #     - "**"
  # pull_request:
  #   branches:
  #     - "**"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Configure git line endings
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v4

      - name: Setup build environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          conda-solver: libmamba
          use-only-tar-bz2: true

      - name: Create environment file
        shell: cmd
        run: |
          echo Creating environment file...
          echo name: rdkit_build > environment.yml
          echo channels: >> environment.yml
          echo   - conda-forge >> environment.yml
          echo dependencies: >> environment.yml
          echo   - boost >> environment.yml
          echo   - boost-cpp >> environment.yml
          echo   - cairo >> environment.yml
          echo   - eigen >> environment.yml
          echo   - cmake >> environment.yml
          echo Environment file created:
          type environment.yml

      - name: Create conda environment
        shell: cmd /C CALL {0}
        run: |
          echo "=== CREATING CONDA ENVIRONMENT ==="
          conda env create -f environment.yml
          echo "Environment creation exit code: %errorlevel%"
          
          if errorlevel 1 (
            echo "ERROR: Failed to create environment from file!"
            echo "=== TRYING MANUAL CREATION ==="
            conda create --name rdkit_build -c conda-forge boost boost-cpp cairo eigen cmake
            echo "Manual creation exit code: %errorlevel%"
          )
          
          echo "=== VERIFYING ENVIRONMENT ==="
          conda info --envs
          conda list -n rdkit_build

      - name: Verify conda environment
        shell: cmd /C CALL {0}
        run: |
          echo "Verifying rdkit_build environment exists..."
          conda info --envs | findstr rdkit_build
          if errorlevel 1 (
            echo "ERROR: rdkit_build environment not found!"
            echo "Available environments:"
            conda info --envs
            exit 1
          )
          echo "Environment found, testing activation..."
          conda activate rdkit_build
          echo "Environment activated successfully!"
          conda list | findstr boost

      - name: Clone main RDKit repo
        run: |
          git clone https://github.com/rdkit/rdkit.git --branch Release_2024_09 --single-branch rdkit --depth=1

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            rdkit/build/CMakeCache.txt
            rdkit/build/CMakeFiles
            rdkit/build/lib
            rdkit/build/bin
          key: ${{ runner.os }}-rdkit-vs-build-${{ hashFiles('**/rdkit_cffi_win_vs.yml') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-rdkit-vs-build-${{ hashFiles('**/rdkit_cffi_win_vs.yml') }}-
            ${{ runner.os }}-rdkit-vs-build-

      - name: Configure build (Run CMake)
        shell: cmd /C CALL {0}
        run: |
          set Boost_ROOT=
          cd rdkit
          mkdir build && cd build
          conda activate rdkit_build
          cmake .. ^
            -G "Visual Studio 17 2022" ^
            -A x64 ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DRDK_BUILD_CFFI_LIB=ON ^
            -DRDK_BUILD_MINIMAL_LIB=ON ^
            -DRDK_CFFI_STATIC=ON ^
            -DRDK_INSTALL_INTREE=ON ^
            -DRDK_INSTALL_STATIC_LIBS=OFF ^
            -DRDK_INSTALL_DLLS_MSVC=ON ^
            -DRDK_BUILD_CPP_TESTS=OFF ^
            -DRDK_BUILD_PYTHON_WRAPPERS=OFF ^
            -DRDK_BUILD_COORDGEN_SUPPORT=ON ^
            -DRDK_BUILD_MAEPARSER_SUPPORT=ON ^
            -DRDK_OPTIMIZE_POPCNT=ON ^
            -DRDK_BUILD_TEST_GZIP=ON ^
            -DRDK_BUILD_FREESASA_SUPPORT=ON ^
            -DRDK_BUILD_AVALON_SUPPORT=ON ^
            -DRDK_BUILD_INCHI_SUPPORT=ON ^
            -DRDK_BUILD_YAEHMOP_SUPPORT=ON ^
            -DRDK_BUILD_XYZ2MOL_SUPPORT=ON ^
            -DRDK_BUILD_CAIRO_SUPPORT=ON ^
            -DRDK_BUILD_THREADSAFE_SSS=ON ^
            -DRDK_BUILD_SWIG_WRAPPERS=OFF ^
            -DRDK_SWIG_STATIC=OFF ^
            -DRDK_TEST_MULTITHREADED=ON ^
            -DRDK_USE_BOOST_SERIALIZATION=ON ^
            -DRDK_USE_BOOST_IOSTREAMS=ON ^
            -DCMAKE_INCLUDE_PATH=%CONDA_PREFIX%/Library/include ^
            -DCMAKE_LIBRARY_PATH=%CONDA_PREFIX%/Library/lib

      - name: Build
        shell: cmd /C CALL {0}
        run: |
          echo "=== STARTING BUILD ==="
          echo "Current directory:"
          cd
          echo "Changing to build directory..."
          cd rdkit/build
          echo "Current directory after cd:"
          cd
          
          echo "=== CONDA ENVIRONMENT ACTIVATION ==="
          echo "Available conda environments:"
          conda info --envs
          echo "Activating rdkit_build environment..."
          conda activate rdkit_build
          echo "Conda activation exit code: %errorlevel%"
          echo "Current conda environment:"
          echo %CONDA_DEFAULT_ENV%
          echo "Conda prefix:"
          echo %CONDA_PREFIX%
          
          echo "=== BUILD DIRECTORY CONTENTS BEFORE BUILD ==="
          dir
          
          echo "=== CHECKING CMAKE AND BUILD TOOLS ==="
          where cmake
          cmake --version
          echo "CMake version exit code: %errorlevel%"
          
          echo "=== RUNNING CMAKE BUILD ==="
          echo "Command: cmake --build . --config Release --target rdkitcffi -j 2 --verbose"
          cmake --build . --config Release --target rdkitcffi -j 2 --verbose
          set BUILD_EXIT_CODE=%errorlevel%
          echo "Build exit code: %BUILD_EXIT_CODE%"
          
          echo "=== BUILD DIRECTORY CONTENTS AFTER BUILD ==="
          dir
          
          echo "=== CHECKING OUTPUT DIRECTORIES ==="
          echo "Checking bin directory:"
          if exist bin (
            echo "bin directory exists:"
            dir bin
            if exist bin\Release (
              echo "bin\Release directory exists:"
              dir bin\Release
            ) else (
              echo "bin\Release directory does not exist"
            )
          ) else (
            echo "bin directory does not exist"
          )
          
          echo "Checking lib directory:"
          if exist lib (
            echo "lib directory exists:"
            dir lib
            if exist lib\Release (
              echo "lib\Release directory exists:"
              dir lib\Release
            ) else (
              echo "lib\Release directory does not exist"
            )
          ) else (
            echo "lib directory does not exist"
          )
          
          # Check if build failed
          if %BUILD_EXIT_CODE% neq 0 (
            echo "=== BUILD FAILED ==="
            echo "Build failed with exit code: %BUILD_EXIT_CODE%"
            echo "Checking for error logs..."
            if exist CMakeFiles\CMakeError.log (
              echo "=== CMakeError.log ==="
              type CMakeFiles\CMakeError.log
            )
            if exist CMakeFiles\CMakeOutput.log (
              echo "=== Last 50 lines of CMakeOutput.log ==="
              powershell -Command "Get-Content CMakeFiles\CMakeOutput.log | Select-Object -Last 50"
            )
            exit %BUILD_EXIT_CODE%
          ) else (
            echo "=== BUILD SUCCESSFUL ==="
          )

      - name: Create build artifacts
        shell: powershell
        run: |
          Write-Host "=== COMPREHENSIVE BUILD DIRECTORY ANALYSIS ==="
          Write-Host "Current working directory:"
          Get-Location
          
          Write-Host "=== CHECKING BUILD DIRECTORY STRUCTURE ==="
          if (Test-Path "rdkit") {
            Write-Host "rdkit directory exists"
            if (Test-Path "rdkit\build") {
              Write-Host "rdkit\build directory exists, contents:"
              Get-ChildItem "rdkit\build" | Format-Table Name, LastWriteTime, Length
              
              Write-Host "=== CHECKING FOR ANY DLL FILES ==="
              Write-Host "All DLL files in build directory:"
              Get-ChildItem "rdkit\build" -Recurse -Filter "*.dll" | Format-Table FullName, LastWriteTime, Length
              
              Write-Host "=== CHECKING FOR ANY RDKITCFFI FILES ==="
              Write-Host "All files containing 'rdkitcffi' or 'cffi':"
              Get-ChildItem "rdkit\build" -Recurse | Where-Object Name -match "rdkitcffi|cffi" | Format-Table FullName, LastWriteTime, Length
              
              Write-Host "=== CHECKING SPECIFIC DIRECTORIES ==="
              @("bin", "lib", "bin\Release", "lib\Release", "bin\Debug", "lib\Debug") | ForEach-Object {
                $dir = "rdkit\build\$_"
                if (Test-Path $dir) {
                  Write-Host "$dir directory exists, contents:"
                  Get-ChildItem $dir | Format-Table Name, LastWriteTime, Length
                } else {
                  Write-Host "$dir directory does not exist"
                }
              }
              
              Write-Host "=== CHECKING CMAKE FILES ==="
              if (Test-Path "rdkit\build\CMakeCache.txt") {
                Write-Host "CMakeCache.txt exists, checking build type and target:"
                Get-Content "rdkit\build\CMakeCache.txt" | Select-String "CMAKE_BUILD_TYPE|CFFI|TARGET"
              }
              
            } else {
              Write-Host "rdkit\build directory does not exist!"
            }
          } else {
            Write-Host "rdkit directory does not exist!"
          }
          
          Write-Host "=== CREATING ARTIFACT DIRECTORY ==="
          New-Item -ItemType Directory -Force -Path "$env:GITHUB_WORKSPACE\rdkitcffi_windows\windows-64"
          Write-Host '-----------------'
          Write-Host 'Looking for DLL files...'
          
          # Look for the DLL file in the bin directory
          if (Test-Path "rdkit\build\bin\Release\librdkitcffi.dll") {
            Write-Host 'Found librdkitcffi.dll in bin\Release directory'
            Get-ChildItem rdkit\build\bin\Release\librdkitcffi.dll
            Set-Location rdkit\build\bin\Release
            $BUILD = (git describe --tags --long HEAD).Split('-')[1]
            Copy-Item librdkitcffi.dll "$env:GITHUB_WORKSPACE\rdkitcffi_windows\windows-64\librdkitcffi.dll.$BUILD"
          } elseif (Test-Path "rdkit\build\bin\Release\rdkitcffi.dll") {
            Write-Host 'Found rdkitcffi.dll in bin\Release directory'
            Get-ChildItem rdkit\build\bin\Release\rdkitcffi.dll
            Set-Location rdkit\build\bin\Release
            $BUILD = (git describe --tags --long HEAD).Split('-')[1]
            Copy-Item rdkitcffi.dll "$env:GITHUB_WORKSPACE\rdkitcffi_windows\windows-64\rdkitcffi.dll.$BUILD"
          } elseif (Test-Path "rdkit\build\lib\Release\librdkitcffi.dll") {
            Write-Host 'Found librdkitcffi.dll in lib\Release directory'
            Get-ChildItem rdkit\build\lib\Release\librdkitcffi.dll
            Set-Location rdkit\build\lib\Release
            $BUILD = (git describe --tags --long HEAD).Split('-')[1]
            Copy-Item librdkitcffi.dll "$env:GITHUB_WORKSPACE\rdkitcffi_windows\windows-64\librdkitcffi.dll.$BUILD"
          } else {
            Write-Host 'DLL file not found in expected locations.'
            Write-Host 'Checking if any DLL was built anywhere:'
            $allDlls = Get-ChildItem "rdkit\build" -Recurse -Filter "*.dll" -ErrorAction SilentlyContinue
            if ($allDlls) {
              Write-Host "Found DLL files in build directory:"
              $allDlls | Format-Table FullName, LastWriteTime, Length
              
              # Look for any CFFI-related DLL
              $cffiDll = $allDlls | Where-Object Name -match "cffi"
              if ($cffiDll) {
                Write-Host "Found CFFI-related DLL, copying it:"
                $cffiDll | Format-Table FullName, LastWriteTime, Length
                $BUILD = (git describe --tags --long HEAD).Split('-')[1]
                Copy-Item $cffiDll[0].FullName "$env:GITHUB_WORKSPACE\rdkitcffi_windows\windows-64\$($cffiDll[0].Name).$BUILD"
              } else {
                Write-Host "No CFFI-related DLL found among built DLLs"
                exit 1
              }
            } else {
              Write-Host "No DLL files found anywhere in build directory"
              exit 1
            }
          }
          
          Write-Host 'Final artifact directory contents:'
          Get-ChildItem "$env:GITHUB_WORKSPACE\rdkitcffi_windows\windows-64\"
          
          Write-Host 'Checking file sizes:'
          Get-ChildItem "$env:GITHUB_WORKSPACE\rdkitcffi_windows\windows-64\" | Format-Table Name, Length

      - name: Create artifact
        run: |
          cd $env:GITHUB_WORKSPACE
          # Check if the directory exists and has files
          if (Test-Path "rdkitcffi_windows") {
            Write-Host "Found rdkitcffi_windows directory, contents:"
            Get-ChildItem -Recurse "rdkitcffi_windows"
            
            # Show current directory and file for debugging
            Write-Host "Current directory:"
            Get-Location
            Write-Host "Directory details:"
            Get-ChildItem "rdkitcffi_windows" | Format-List
          } else {
            Write-Host "ERROR: rdkitcffi_windows directory not found!"
            Get-ChildItem
            exit 1
          }

      - name: Verify directory exists
        run: |
          Write-Host "Current directory:"
          Get-Location
          Write-Host "Files in current directory:"
          Get-ChildItem
          Write-Host "Checking for rdkitcffi_windows directory:"
          if (Test-Path "rdkitcffi_windows") {
            Write-Host "✅ Directory found!"
            Get-ChildItem "rdkitcffi_windows" -Recurse
          } else {
            Write-Host "❌ Directory not found!"
            exit 1
          }

      - name: Upload artifact to GitHub Actions
        uses: actions/upload-artifact@v4
        with:
          name: rdkitcffi_windows_vs
          path: rdkitcffi_windows
          retention-days: 30

      - name: Create Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          files: rdkitcffi_windows
          tag_name: rdkit-windows-vs-latest
          name: Latest RDKit CFFI Windows VS Build
          body: Automated RDKit CFFI Windows DLL build using Visual Studio
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 