name: RDKit CFFI Windows 2024.09

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with debug logging'
        required: false
        default: false
        type: boolean
  # push:
  #   branches:
  #     - "**"
  # pull_request:
  #   branches:
  #     - "**"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Configure git line endings
        run: git config --global core.autocrlf input

      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            base-devel
            git
            cmake
            mingw-w64-ucrt-x86_64-boost
            mingw-w64-ucrt-x86_64-cairo
            mingw-w64-ucrt-x86_64-zlib
            mingw-w64-ucrt-x86_64-xz
            mingw-w64-ucrt-x86_64-gcc
            mingw-w64-ucrt-x86_64-make
            mingw-w64-ucrt-x86_64-pkg-config
          pacboy: >-
            toolchain:p

      - name: Clone main RDKit repo
        shell: msys2 {0}
        run: |
          git clone https://github.com/rdkit/rdkit.git --branch Release_2024_09 --single-branch rdkit --depth=1

      - name: Configure build (Run CMake)
        shell: msys2 {0}
        run: |
          cd rdkit && mkdir build && cd build
          cmake .. \
            -G 'MSYS Makefiles' \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DRDK_INSTALL_INTREE=OFF \
            -DRDK_INSTALL_STATIC_LIBS=OFF \
            -DRDK_BUILD_CPP_TESTS=ON \
            -DRDK_BUILD_COORDGEN_SUPPORT=ON \
            -DRDK_BUILD_MAEPARSER_SUPPORT=ON \
            -DRDK_OPTIMIZE_POPCNT=ON \
            -DRDK_BUILD_TEST_GZIP=ON \
            -DRDK_BUILD_FREESASA_SUPPORT=ON \
            -DRDK_BUILD_AVALON_SUPPORT=ON \
            -DRDK_BUILD_INCHI_SUPPORT=ON \
            -DRDK_BUILD_CAIRO_SUPPORT=ON \
            -DRDK_BUILD_CFFI_LIB=ON \
            -DRDK_CFFI_STATIC=OFF \
            -DRDK_BUILD_THREADSAFE_SSS=ON \
            -DRDK_BUILD_SWIG_WRAPPERS=OFF \
            -DRDK_SWIG_STATIC=OFF \
            -DRDK_TEST_MULTITHREADED=ON \
            -DRDK_INSTALL_DLLS_MSVC=ON \
            -DRDK_BUILD_PYTHON_WRAPPERS=OFF \
            -DRDK_BUILD_PGSQL=OFF \
            -DRDK_PGSQL_STATIC=OFF \
            -DCAIRO_INCLUDE_DIR=/c/msys64/ucrt64/include \
            -DCAIRO_LIBRARIES=/c/msys64/ucrt64/lib/libcairo.dll.a \
            -DCMAKE_INSTALL_PREFIX=/c/msys64/ucrt64 \
            -DCMAKE_INCLUDE_PATH='/c/msys64/ucrt64/include;/c/msys64/ucrt64/x86_64-w64-mingw32/include' \
            -DCMAKE_LIBRARY_PATH='/c/msys64/ucrt64/lib;/c/msys64/ucrt64/x86_64-w64-mingw32/lib'

      - name: Build
        shell: msys2 {0}
        run: |
          cd rdkit/build
          mingw32-make VERBOSE=1 -j 2 cffi_test
          # If build fails, show the error log
          if [ $? -ne 0 ]; then
            echo 'Build failed. Showing last 100 lines of error log:'
            cat CMakeFiles/CMakeError.log | tail -n 100
            exit 1
          fi

      - name: Run tests
        shell: msys2 {0}
        run: |
          cd rdkit
          export RDBASE=$PWD
          export PATH=${RDBASE}/build/lib:$PATH
          echo 'PATH: ' $PATH
          cd build
          # Try different possible test executable locations
          if [ -f './Code/MinimalLib/cffi_test.exe' ]; then
            ./Code/MinimalLib/cffi_test.exe
          elif [ -f './Code/MinimalLib/cffi_test' ]; then
            ./Code/MinimalLib/cffi_test
          else
            echo 'Test executable not found. Looking for it:'
            find . -name '*cffi_test*' -type f
            exit 1
          fi

      - name: Create build artifacts
        shell: msys2 {0}
        run: |
          mkdir -p $GITHUB_WORKSPACE/rdkitcffi_windows/windows-64
          echo '-----------------'
          # Look for the DLL file with different possible names
          if [ -f 'rdkit/build/lib/rdkitcffi.dll' ]; then
            ls -l rdkit/build/lib/rdkitcffi.dll
            cd rdkit/build/lib
            BUILD=$(cd ../.. && git describe --tags --long HEAD | cut -d '-' -f 2)
            cp rdkitcffi.dll $GITHUB_WORKSPACE/rdkitcffi_windows/windows-64/rdkitcffi.dll.$BUILD
          elif [ -f 'rdkit/build/lib/librdkitcffi.dll' ]; then
            ls -l rdkit/build/lib/librdkitcffi.dll
            cd rdkit/build/lib
            BUILD=$(cd ../.. && git describe --tags --long HEAD | cut -d '-' -f 2)
            cp librdkitcffi.dll $GITHUB_WORKSPACE/rdkitcffi_windows/windows-64/librdkitcffi.dll.$BUILD
          else
            echo 'DLL file not found. Listing lib directory:'
            ls -la rdkit/build/lib/
            exit 1
          fi
          ls -l $GITHUB_WORKSPACE/rdkitcffi_windows/windows-64

      - name: Create artifact
        run: |
          cd $env:GITHUB_WORKSPACE
          Compress-Archive -Path "rdkitcffi_windows" -DestinationPath "rdkitcffi_windows.zip"

      - name: Create Release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/rdkitcffi_windows.zip
          tag_name: rdkit-windows-latest
          name: Latest RDKit CFFI Windows Build
          body: Automated RDKit CFFI Windows DLL build
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 