name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install build dependencies
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git g++ gcc wget make cmake libboost-all-dev libfreetype6-dev liblzma-dev

      # Build Boost static libraries
      - name: Build Boost
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.gz
          tar xzf boost_1_83_0.tar.gz
          cd boost_1_83_0
          ./bootstrap.sh --with-libraries=serialization,system,iostreams
          ./b2 link=static runtime-link=shared threading=multi
          cd ..

      # Build RDKit with static Boost
      - name: Build RDKit
        run: |
          git clone https://github.com/rdkit/rdkit.git --branch Release_2024_09 --single-branch rdkit --depth=1
          cd rdkit
          mkdir build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DRDK_BUILD_CPP_TESTS=OFF \
            -DRDK_BUILD_PYTHON_WRAPPERS=OFF \
            -DRDK_BUILD_COORDGEN_SUPPORT=ON \
            -DRDK_BUILD_MAEPARSER_SUPPORT=ON \
            -DRDK_OPTIMIZE_POPCNT=ON \
            -DRDK_BUILD_INCHI_SUPPORT=ON \
            -DRDK_BUILD_THREADSAFE_SSS=ON \
            -DRDK_TEST_MULTITHREADED=ON \
            -DRDK_BUILD_CFFI_LIB=ON \
            -DDOWNLOAD_INCHI_DEP=ON \
            -DBoost_USE_STATIC_LIBS=ON \
            -DBOOST_ROOT=$GITHUB_WORKSPACE/boost_1_83_0 \
            -DBoost_NO_SYSTEM_PATHS=ON
          make -j 2 cffi_test

      # Set up environment variables and copy libraries
      - name: Setup RDKit environment
        run: |
          echo "RDBASE=$GITHUB_WORKSPACE/rdkit" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$GITHUB_WORKSPACE/rdkit/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          
          # Create directory structure
          mkdir -p $GITHUB_WORKSPACE/rdkitcffi_linux/linux-64
          
          # Copy RDKit CFFI library
          cp rdkit/build/lib/librdkitcffi.so.1.* $GITHUB_WORKSPACE/rdkitcffi_linux/linux-64/
          cd $GITHUB_WORKSPACE/rdkitcffi_linux/linux-64
          ln -s librdkitcffi.so.1.* librdkitcffi.so
          ln -s librdkitcffi.so.1.* librdkitcffi.so.1

      # Create and publish artifact
      - name: Create artifact
        run: |
          cd $GITHUB_WORKSPACE
          tar czf rdkitcffi_linux.tar.gz rdkitcffi_linux/

      - name: Create Release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/lib/rdkitcffi_linux.tar.gz
          tag_name: rdkit-latest
          name: Latest RDKit CFFI Build
          body: Automated RDKit CFFI library build
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Rust build steps after library is ready
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy

      - name: Build
        run: |
          cargo build --verbose

      - name: Test
        run: |
          cargo check
          cargo test --all --verbose

      

